# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a975a86f938a666dad2c6e0b46d087b08bd449025002861fd2bbf6098c82cb9f64adcbcd5689ceec5c3ae8a7df65f1e05093214b3592a6430b9e36e07e13ce30

test:
  secret_key_base: 85343054e6fae3678939f8af4817abb68dc27ed879667f000bbd371d367509632dbd60d05ef63109f37df680ad44acb47245302acbe530001933fcb97ea2da35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
